files:
  includes:
  - getting-started/quick-start.txt
  - getting-started/faq.txt
  - getting-started/alt1.txt
  - getting-started/requirements.txt
  - getting-started/useful-links.txt
  - getting-started/useful-unlocks.txt
  - gathering-clues/easy-gathering.txt
  - gathering-clues/medium-gathering.txt
  - gathering-clues/hard-gathering/*.txt
  - gathering-clues/elite-gathering/*.txt
  - gathering-clues/master-gathering.txt
  - gathering-clues/scripture-of-bik-gathering/*.txt
  - solving-clues/easy-clue-guide.txt
  - solving-clues/medium-clue-guide.txt
  - solving-clues/hard-clue-guide.txt
  - solving-clues/elite-clue-guide.txt
  - solving-clues/master-clue-guide.txt
  - hall-of-fame/explanation.txt
  - hall-of-fame/golden-clue-titles.txt
  - hall-of-fame/golden-clue-title-progress.txt
  - hall-of-fame/most-of-a-broadcast.txt
  - hall-of-fame/other-accomplishments.txt
