files:
  includes:
  - getting-started/quick-start.txt
  - getting-started/faq.txt
  - getting-started/alt1.txt
  - getting-started/requirements.txt
  - getting-started/useful-links.txt
  - getting-started/useful-unlocks.txt
  - gathering-clues/easy-gathering.txt
  - gathering-clues/medium-gathering.txt
  - gathering-clues/hard-gathering/*.txt
  - gathering-clues/elite-gathering/*.txt
  - gathering-clues/master-gathering.txt
  - gathering-clues/scripture-of-bik-gathering/*.txt
  - solving-clues/**/*.txt
  - hall-of-fame/**/*.txt
