name: test-build

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Setup pipenv virtual environment
        run: |
          echo hello
